import { SiteNav } from '@/components/layout/SiteNav';import { ButterflyScene } from '@/components/3d/ButterflyScene';
const shell=(title:string,body:React.ReactNode)=><main className="min-h-screen bg-[#EEF3E8] text-[#1E1A16]"><SiteNav/><section className="mx-auto max-w-6xl px-6 py-32"><h1 className="font-serif text-6xl">{title}</h1><div className="mt-8 text-lg leading-relaxed">{body}</div></section></main>;
export const Journey=()=>shell('El Viaje',<><p>Ruta interactiva de Monarcas migratorias y Morphos tropicales con educación segura.</p><ButterflyScene/></>);
export const Monarch=()=>shell('Viaje Monarca',<p>Las orugas de Monarca dependen de milkweed / Asclepias. Su migración es sensible y no promovemos captura ni liberación sin permisos.</p>);
export const Morpho=()=>shell('Viaje Morpho',<p>Nuestro programa de Morphos se desarrolla con validación biológica y cumplimiento legal. Primero protegemos el hábitat; después criamos solamente cuando la especie, el origen y los permisos estén confirmados.</p>);
export const Garden=()=>shell('Estación Monarcas y Morphos — Puerto Vallarta',<div className="grid gap-4 md:grid-cols-2">{['host plants planted','butterflies observed','school visits','lifecycle logs','release events (solo aprobados)','volunteer days','garden health','donor impact'].map(x=><div className="rounded-2xl bg-[#F5E8D0] p-5" key={x}>{x}</div>)}</div>);
export const Schools=()=>shell('Escuelas',<><p>Misiones de aula: Encuentra una planta hospedera, Observa una hoja, Identifica huevos, Cuida una oruga, Registra una crisálida, Celebra el primer vuelo, Planta una flor de néctar, Reporta un avistamiento.</p><p className="mt-4">Badges: Guardián de la Monarca, Explorador Morpho, Cuidador de Orugas, Protector de Plantas Hospederas, Científico Ciudadano, Jardín Vivo, Primer Vuelo. Incluye consentimiento parental e instrucciones de manejo seguro.</p></>);
export const Participate=()=>shell('Participa',<p>Voluntariado, donaciones, reportes de avistamiento y patrocinio de plantas hospederas con verificación responsable.</p>);
export const Legal=()=>shell('Legal y conservación',<><p className="rounded-2xl bg-[#F5E8D0] p-6 font-semibold">No promovemos la captura, transporte, importación, exportación, crianza o liberación de mariposas sin permisos y validación biológica. Nuestro trabajo comienza con educación, restauración de hábitat, plantas hospederas, ciencia ciudadana y alianzas responsables.</p><ol className="mt-6 list-decimal pl-6">{['Confirmar especie exacta','Confirmar rango local/nativo','Confirmar origen legal de huevos/larvas/pupas','Confirmar plantas hospederas','Confirmar protocolo sanitario','Confirmar ubicación de liberación','Confirmar ruta SEMARNAT/UMA','Guardar permisos','Revisión de administrador','Mostrar estatus público'].map(x=><li key={x}>{x}</li>)}</ol></>);
