import { useState, type FormEvent } from 'react';
import { Camera, Crosshair, Save, ShieldCheck } from 'lucide-react';
import { species } from '@/data/species';

export function ObservationDraft() {
  const [lat,setLat]=useState(''); const [lng,setLng]=useState(''); const [status,setStatus]=useState('');
  const locate=()=>{ if(!navigator.geolocation){setStatus('Geolocation is not available on this device.');return;} navigator.geolocation.getCurrentPosition(({coords})=>{setLat(coords.latitude.toFixed(6));setLng(coords.longitude.toFixed(6));setStatus('Location captured. Nothing has been uploaded.');},()=>setStatus('Location permission was not granted.'),{enableHighAccuracy:true,timeout:10000}); };
  const saveDraft=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const draft={taxon:form.get('taxon'),observed_at:form.get('observed_at'),notes:form.get('notes'),latitude:lat||null,longitude:lng||null,saved_at:new Date().toISOString(),verification_status:'draft'};localStorage.setItem('morphos-observation-draft',JSON.stringify(draft));setStatus('Draft saved on this device. It has NOT been submitted to a research database.');};
  return <section id="observar" className="morphos-observation-shell"><div className="morphos-observation-copy"><span className="morphos-eyebrow">CIENCIA CIUDADANA · PROTOTIPO</span><h2>Convierte un encuentro en evidencia.</h2><p>El formulario guarda únicamente un borrador local hasta conectar y verificar el proyecto Supabase definitivo.</p><div className="morphos-truth-note"><ShieldCheck size={18}/> IA sugerida ≠ identificación verificada.</div></div><form className="morphos-observation-form" onSubmit={saveDraft}><label>Especie observada o sugerida<select name="taxon" defaultValue="unknown"><option value="unknown">No estoy seguro todavía</option>{species.map((item)=><option key={item.id} value={item.scientificName}>{item.scientificName} — {item.commonNameEs}</option>)}</select></label><label>Fecha y hora<input type="datetime-local" name="observed_at"/></label><div className="morphos-location-row"><button type="button" className="morphos-secondary-action" onClick={locate}><Crosshair size={17}/> Usar mi ubicación</button><span>{lat&&lng?`${lat}, ${lng}`:'sin coordenadas'}</span></div><label>Notas de campo<textarea name="notes" rows={4} placeholder="Planta, comportamiento, clima, hábitat, amenazas visibles…"/></label><div className="morphos-field-actions"><button type="button" className="morphos-secondary-action" disabled title="La carga de fotografías se habilitará al conectar el backend"><Camera size={17}/> Foto — pendiente backend</button><button type="submit" className="morphos-primary-action"><Save size={17}/> Guardar borrador local</button></div>{status&&<p className="morphos-form-status" role="status">{status}</p>}</form></section>;
}
